server:
  port: 8081

mongo:
  uri: mongoUri
  database: mongoDatabase

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springfraemwork.data.mongodb.repository.Query: DEBUG